"""
Маппер для перевода английских названий продуктов на русский язык
"""

FOOD_NAME_RU = {
    # Хлеб и выпечка
    'bread-5-grain': 'Мультизерновой хлеб',
    'bread-black': 'Чёрный хлеб',
    'bread-french-white-flour': 'Французский хлеб',
    'bread-fruit': 'Фруктовый хлеб',
    'bread-grain': 'Зерновой хлеб',
    'bread-half-white': 'Белый хлеб',
    'bread-meat-substitute-lettuce-sauce': 'Сэндвич',
    'bread-nut': 'Ореховый хлеб',
    'bread-olive': 'Хлеб с оливками',
    'bread-pita': 'Пита',
    'bread-rye': 'Ржаной хлеб',
    'bread-sourdough': 'Хлеб на закваске',
    'bread-spelt': 'Спельтовый хлеб',
    'bread-ticino': 'Хлеб',
    'bread-toast': 'Тост',
    'bread-white': 'Белый хлеб',
    'bread-whole-wheat': 'Цельнозерновой хлеб',
    'bread-wholemeal': 'Цельнозерновой хлеб',
    'bread-wholemeal-toast': 'Цельнозерновой тост',
    'braided-white-loaf': 'Плетёный хлеб',

    # Овощи
    'beetroot-raw': 'Свёкла сырая',
    'beetroot-steamed-without-addition-of-salt': 'Свёкла варёная',
    'bell-pepper-red-raw': 'Красный болгарский перец',
    'bell-pepper-red-stewed-without-addition-of-fat-without-addition-of-salt': 'Тушёный перец',
    'carrot-raw': 'Морковь сырая',
    'carrot-steamed-without-addition-of-salt': 'Морковь варёная',
    'green-bean-steamed-without-addition-of-salt': 'Стручковая фасоль',
    'mushroom-average-stewed-without-addition-of-fat-without-addition-of-salt': 'Тушёные грибы',
    'savoy-cabbage-steamed-without-addition-of-salt': 'Тушёная капуста',
    'spinach-raw': 'Шпинат свежий',
    'spinach-steamed-without-addition-of-salt': 'Шпинат тушёный',
    'tomato-raw': 'Помидор свежий',
    'tomato-stewed-without-addition-of-fat-without-addition-of-salt': 'Тушёные томаты',
    'zucchini-stewed-without-addition-of-fat-without-addition-of-salt': 'Тушёный кабачок',

    # Мясо
    'beef-cut-into-stripes-only-meat': 'Говядина соломкой',
    'beef-filet': 'Говяжье филе',
    'beef-minced-only-meat': 'Говяжий фарш',
    'beef-roast': 'Ростбиф',
    'beef-sirloin-steak': 'Стейк из говядины',
    'chicken-cut-into-stripes-only-meat': 'Куриное филе соломкой',
    'chicken-curry-cream-coconut-milk-curry-spices-paste': 'Курица карри',
    'cordon-bleu-from-pork-schnitzel-fried': 'Кордон блю',
    'goat-average-raw': 'Козлятина',
    'smoked-cooked-sausage-of-pork-and-beef-meat-sausag': 'Копчёная колбаса',

    # Бекон
    'bacon-cooking': 'Бекон варёный',
    'bacon-frying': 'Бекон жареный',
    'bacon-raw': 'Бекон сырой',

    # Сыры
    'blue-mould-cheese': 'Сыр с плесенью',
    'cheese-for-raclette': 'Сыр раклет',
    'curds-natural-with-at-most-10-fidm': 'Творог',
    'emmental-cheese': 'Сыр эмменталь',
    'faux-mage-cashew-vegan-chers': 'Веганский сыр',
    'goat-cheese-soft': 'Козий сыр',
    'greek-yaourt-yahourt-yogourt-ou-yoghourt': 'Греческий йогурт',
    'hard-cheese': 'Твёрдый сыр',
    'semi-hard-cheese': 'Полутвёрдый сыр',
    'soft-cheese': 'Мягкий сыр',
    'soya-yaourt-yahourt-yogourt-ou-yoghourt': 'Соевый йогурт',
    'yaourt-yahourt-yogourt-ou-yoghourt-natural': 'Йогурт натуральный',

    # Напитки
    'aperitif-with-alcohol-aperol-spritz': 'Апероль шприц',
    'chocolate-milk-chocolate-drink': 'Шоколадное молоко',
    'coca-cola': 'Кока-кола',
    'coca-cola-zero': 'Кола зеро',
    'coffee-decaffeinated': 'Кофе без кофеина',
    'coffee-with-caffeine': 'Кофе',
    'espresso-with-caffeine': 'Эспрессо',
    'glucose-drink-50g': 'Глюкозный напиток',
    'juice-apple': 'Яблочный сок',
    'juice-multifruit': 'Мультифруктовый сок',
    'juice-orange': 'Апельсиновый сок',
    'kefir-drink': 'Кефир',
    'latte-macchiato-with-caffeine': 'Латте макиато',
    'light-beer': 'Светлое пиво',
    'oat-milk': 'Овсяное молоко',
    'ristretto-with-caffeine': 'Ристретто',
    'soya-drink-soy-milk': 'Соевое молоко',
    'syrup-diluted-ready-to-drink': 'Сироп',
    'water-mineral': 'Минеральная вода',
    'water-with-lemon-juice': 'Вода с лимоном',
    'white-coffee-with-caffeine': 'Кофе с молоком',
    'wine-red': 'Красное вино',
    'wine-rose': 'Розовое вино',
    'wine-white': 'Белое вино',

    # Паста
    'high-protein-pasta-made-of-lentils-peas': 'Протеиновая паста',
    'pasta-hornli': 'Паста',
    'pasta-in-butterfly-form-farfalle': 'Фарфалле',
    'pasta-in-conch-form': 'Ракушки (паста)',
    'pasta-linguini-parpadelle-tagliatelle': 'Лингвини',
    'pasta-noodles': 'Лапша',
    'pasta-penne': 'Пенне',
    'pasta-ravioli-stuffing': 'Равиоли',
    'pasta-spaghetti': 'Спагетти',
    'pasta-tortelloni-stuffing': 'Тортеллони',
    'pasta-twist': 'Фузилли',
    'pasta-wholemeal': 'Цельнозерновая паста',

    # Рис
    'rice-basmati': 'Рис басмати',
    'rice-jasmin': 'Рис жасмин',
    'rice-noodles-vermicelli': 'Рисовая лапша',
    'rice-waffels': 'Рисовые хлебцы',
    'rice-whole-grain': 'Бурый рис',
    'rice-wild': 'Дикий рис',

    # Картофель
    'baked-potato': 'Запечённый картофель',
    'country-fries': 'Картофель фри',
    'chips-french-fries': 'Картофель фри',
    'mashed-potatoes-prepared-with-full-fat-milk-with-butter': 'Картофельное пюре',
    'potato-gnocchi': 'Ньокки',
    'potato-salad-with-mayonnaise-yogurt-dressing': 'Картофельный салат',
    'potatoes-au-gratin-dauphinois-prepared': 'Картофель гратен',
    'potatoes-steamed': 'Отварной картофель',

    # Супы
    'soup-cream-of-vegetables': 'Крем-суп овощной',
    'soup-miso': 'Мисо суп',
    'soup-of-lentils-dahl-dhal': 'Чечевичный суп',
    'soup-potato': 'Картофельный суп',
    'soup-pumpkin': 'Тыквенный суп',
    'soup-tomato': 'Томатный суп',
    'soup-vegetable': 'Овощной суп',

    # Соусы
    'balsamic-salad-dressing': 'Бальзамический соус',
    'balsamic-vinegar': 'Бальзамический уксус',
    'bolognaise-sauce': 'Соус болоньезе',
    'french-salad-dressing': 'Французская заправка',
    'hazelnut-chocolate-spread-nutella-ovomaltine-caotina': 'Нутелла',
    'italian-salad-dressing': 'Итальянская заправка',
    'oil-vinegar-salad-dressing': 'Винегрет (заправка)',
    'sauce-carbonara': 'Соус карбонара',
    'sauce-cocktail': 'Коктейльный соус',
    'sauce-cream': 'Сливочный соус',
    'sauce-curry': 'Соус карри',
    'sauce-mushroom': 'Грибной соус',
    'sauce-pesto': 'Песто',
    'sauce-roast': 'Мясной соус',
    'sauce-savoury': 'Пикантный соус',
    'sauce-soya': 'Соевый соус',
    'sauce-sweet-salted-asian': 'Кисло-сладкий соус',
    'sauce-sweet-sour': 'Кисло-сладкий соус',
    'tartar-sauce': 'Соус тартар',
    'tomato-sauce': 'Томатный соус',

    # Фрукты
    'apple': 'Яблоко',
    'apricot': 'Абрикос',
    'apricot-dried': 'Курага',
    'avocado': 'Авокадо',
    'banana': 'Банан',
    'blueberries': 'Черника',
    'cherries': 'Вишня',
    'clementine': 'Клементин',
    'dates': 'Финики',
    'fig': 'Инжир',
    'fig-dried': 'Инжир сушёный',
    'grapes': 'Виноград',
    'grapefruit-pomelo': 'Грейпфрут',
    'kiwi': 'Киви',
    'lemon': 'Лимон',
    'mango': 'Манго',
    'orange': 'Апельсин',
    'papaya': 'Папайя',
    'peach': 'Персик',
    'pear': 'Груша',
    'pineapple': 'Ананас',
    'plums': 'Слива',
    'pomegranate': 'Гранат',
    'raspberries': 'Малина',
    'strawberries': 'Клубника',
    'sugar-melon': 'Дыня',
    'tangerine': 'Мандарин',
    'watermelon-fresh': 'Арбуз',

    # Орехи
    'almonds': 'Миндаль',
    'brazil-nut': 'Бразильский орех',
    'cashew-nut': 'Кешью',
    'hazelnut': 'Фундук',
    'macadamia-nut': 'Макадамия',
    'peanut': 'Арахис',
    'pecan-nut': 'Пекан',
    'pine-nuts': 'Кедровые орехи',
    'pistachio': 'Фисташки',
    'walnut': 'Грецкий орех',

    # Десерты
    'apple-crumble': 'Яблочный крамбл',
    'apple-pie': 'Яблочный пирог',
    'banana-cake': 'Банановый кекс',
    'black-forest-tart': 'Шварцвальдский торт',
    'cake-chocolate': 'Шоколадный торт',
    'cake-marble': 'Мраморный кекс',
    'cake-oblong': 'Кекс',
    'cake-salted': 'Солёный пирог',
    'carrot-cake': 'Морковный торт',
    'chocolate-mousse': 'Шоколадный мусс',
    'lemon-cake': 'Лимонный кекс',
    'lemon-pie': 'Лимонный пирог',
    'pie-apricot-baked-with-cake-dough': 'Абрикосовый пирог',
    'pie-plum-baked-with-cake-dough': 'Сливовый пирог',
    'pie-rhubarb-baked-with-cake-dough': 'Пирог с ревенем',
    'dairy-ice-cream': 'Мороженое',
    'panna-cotta': 'Панна котта',
    'vanille-cream-cooked-custard-creme-dessert': 'Ванильный крем',

    # Пицца
    'french-pizza-from-alsace-baked': 'Пицца',
    'pizza-margherita-baked': 'Пицца Маргарита',
    'pizza-with-ham-baked': 'Пицца с ветчиной',
    'pizza-with-ham-with-mushrooms-baked': 'Пицца с ветчиной и грибами',
    'pizza-with-vegetables-baked': 'Пицца с овощами',

    # Завтраки
    'birchermuesli-prepared-no-sugar-added': 'Мюсли',
    'corn-flakes': 'Кукурузные хлопья',
    'crunch-muesli': 'Хрустящие мюсли',
    'flakes-oat': 'Овсяные хлопья',
    'porridge-prepared-with-partially-skimmed-milk': 'Овсяная каша',

    # Яйца
    'egg': 'Яйцо',
    'egg-scrambled-prepared': 'Яичница-болтунья',
    'omelette-plain': 'Омлет',
    'fried-egg-without-addition-of-fat': 'Яичница',

    # Салаты
    'caprese-salad-tomato-mozzarella': 'Салат Капрезе',
    'coleslaw-chopped-without-sauce': 'Коулслоу',
    'greek-salad': 'Греческий салат',
    'mixed-salad-chopped-without-sauce': 'Овощной салат',
    'salad-lambs-ear': 'Салат корн',
    'salad-leaf-salad-green': 'Зелёный салат',
    'salad-rocket': 'Салат с рукколой',
    'taboule-prepared-with-couscous': 'Табуле',

    # Гамбургеры и сэндвичи
    'hamburger-bread-meat-ketchup': 'Гамбургер',
    'hamburger-bun': 'Булочка для бургера',
    'sandwich-ham-cheese-and-butter': 'Сэндвич с ветчиной и сыром',
    'croque-monsieur': 'Крок-месье',
    'kebab-in-pita-bread': 'Кебаб в пите',

    # Готовые блюда
    'cantonese-fried-rice': 'Жареный рис',
    'chili-con-carne-prepared': 'Чили кон карне',
    'curry-vegetarian': 'Овощное карри',
    'lasagne-meat-prepared': 'Лазанья с мясом',
    'lasagne-vegetable-prepared': 'Овощная лазанья',
    'quiche-with-cheese-baked-with-puff-pastry': 'Киш с сыром',
    'quiche-with-spinach-baked-with-cake-dough': 'Киш со шпинатом',
    'risotto-with-mushrooms-cooked': 'Ризотто с грибами',
    'risotto-without-cheese-cooked': 'Ризотто',

    # Морепродукты
    'fish-crunchies-battered': 'Рыбные наггетсы',
    'fish-fingers-breaded': 'Рыбные палочки',
    'salmon': 'Лосось',
    'salmon-smoked': 'Копчёный лосось',
    'shrimp-prawn-large': 'Креветки',
    'tuna': 'Тунец',
    'tuna-in-oil-drained': 'Тунец в масле',
    'perch-fillets-lake': 'Филе окуня',

    # Другое
    'bagel-without-filling': 'Бейгл',
    'biscuit-with-butter': 'Печенье',
    'breadcrumbs-unspiced': 'Панировочные сухари',
    'buckwheat-grain-peeled': 'Гречка',
    'buckwheat-pancake': 'Гречневый блин',
    'butter': 'Сливочное масло',
    'butter-herb': 'Масло с травами',
    'butter-spread-puree-almond': 'Миндальная паста',
    'chicken-nuggets': 'Куриные наггетсы',
    'chocolate': 'Шоколад',
    'chocolate-cookies': 'Шоколадное печенье',
    'chocolate-egg-small': 'Шоколадное яйцо',
    'chocolate-filled': 'Шоколад с начинкой',
    'corn-crisps': 'Кукурузные чипсы',
    'crisp-bread-wasa': 'Хрустящие хлебцы',
    'croissant': 'Круассан',
    'croissant-wholegrain': 'Цельнозерновой круассан',
    'croissant-with-chocolate-filling': 'Круассан с шоколадом',
    'dough-puff-pastry-shortcrust-bread-pizza-dough': 'Тесто',
    'dried-raisins': 'Изюм',
    'fajita-bread-only': 'Фахита',
    'falafel-balls': 'Фалафель',
    'gluten-free-bread': 'Безглютеновый хлеб',
    'gummi-bears-fruit-jellies-jelly-babies-with-fruit-essence': 'Мармеладные мишки',
    'honey': 'Мёд',
    'hummus': 'Хумус',
    'jam': 'Джем',
    'lentils-green-du-puy-du-berry': 'Чечевица',
    'lye-pretzel-soft': 'Брецель',
    'm-m-s': 'M&M\'s',
    'maple-syrup-concentrate': 'Кленовый сироп',
    'mayonnaise': 'Майонез',
    'meat-terrine-pate': 'Паштет',
    'milk': 'Молоко',
    'milk-chocolate': 'Молочный шоколад',
    'milk-chocolate-with-hazelnuts': 'Шоколад с фундуком',
    'mix-of-dried-fruits-and-nuts': 'Смесь орехов и сухофруктов',
    'mozzarella': 'Моцарелла',
    'olive': 'Оливки',
    'onion': 'Лук',
    'parmesan': 'Пармезан',
    'peanut-butter': 'Арахисовая паста',
    'popcorn-salted': 'Попкорн солёный',
    'roll-of-half-white-or-white-flour-with-large-void': 'Булочка',
    'roll-with-pieces-of-chocolate': 'Булочка с шоколадом',
    'spring-roll-fried': 'Спринг-ролл',
    'sweet-corn-canned': 'Консервированная кукуруза',
    'sweet-potato': 'Батат',
    'sweets-candies': 'Конфеты',
    'tofu': 'Тофу',
    'turnover-with-meat-small-meat-pie-empanadas': 'Эмпанада',
    'veggie-burger': 'Веган бургер',
    'white-bread-with-butter-eggs-and-milk': 'Бриошь',
    'wienerli-swiss-sausage': 'Сосиска',
}


def get_russian_name(model_output: str) -> str:
    """
    Возвращает русское название продукта по выходу модели

    Args:
        model_output: Название продукта из модели

    Returns:
        Русское название или оригинальное с заменой дефисов на пробелы
    """
    if not model_output:
        return "Неизвестный продукт"

    if model_output in FOOD_NAME_RU:
        return FOOD_NAME_RU[model_output]

    # Если нет в словаре - заменяем дефисы на пробелы
    return model_output.replace('-', ' ').title()
